
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATAPS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Activity
{

    public int ID { get; set; }

    public string ActivityName { get; set; }

    public int AgendaID { get; set; }

    public Nullable<int> ActivityTypeID { get; set; }

}

}
