//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int ID { get; set; }
        public int EventDateID { get; set; }
        public string AgendaName { get; set; }
        public Nullable<short> AgendaOrder { get; set; }
        public byte AgendaType { get; set; }
    }
}
