//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCheckIn
    {
        public int rideID { get; set; }
        public string activity { get; set; }
        public Nullable<int> busNumber { get; set; }
        public Nullable<int> partID { get; set; }
        public string chrDirection { get; set; }
        public Nullable<byte> stopNmbr { get; set; }
    }
}
