
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ATAPS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EventDate
{

    public int ID { get; set; }

    public Nullable<System.DateTime> EventDate1 { get; set; }

    public int EventRecordsID { get; set; }

}

}
