//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCard
    {
        public int ID { get; set; }
        public Nullable<int> ParticipantID { get; set; }
        public string ccNumber { get; set; }
        public byte[] signature { get; set; }
    }
}
