//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public bool CheckIn { get; set; }
        public bool CheckOut { get; set; }
        public bool AttendeeLimit { get; set; }
    }
}
